export const optionNames = [
  'setup',
  'draw',
  'preload',
  'mousePressed',
  'mouseMoved',
  'mouseReleased',
  'mouseDragged',
  'mouseClicked',
  'doubleClicked',
  'mouseWheel',
  'keyPressed',
  'keyReleased',
  'keyReleased',
  'deviceMoved',
  'deviceShaken',
  'deviceTurned',
  'windowResized',
] as const
